exports.YOUDAO_AUTHORIZATION_KEY = 'YOUDAO_AUTHORIZATION_KEY';
exports.DEEPL_AUTHORIZATION_KEY = 'DEEPL_AUTHORIZATION_KEY';
exports.USE_TRANSLATE = 'USE_TRANSLATE';
exports.TINIFY_AUTHORIZATION_KEY = 'TINIFY_AUTHORIZATION_KEY';

exports.supports = { youdao: 'youdao', deepl: 'deepl' };
